### ISSUE TITLE
Migration Issue

### ISSUE THREAD

**Issue by basuregami** [josecelano/ddd-laravel-sample#1]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laracasts](https://laracasts.com/discuss/) or [laravel](http://laravel.io/forum) forums.
- You have read the [wiki](https://github.com/rappasoft/laravel-5-boilerplate/wiki) thoroughly.
- You have searched for a similar issues among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

# What version?
Please when it's necessary, provide the version of your copy of the boilerplate. You can find the version number in the original README.md.

**Comment by basuregami** [comment]
Illuminate\Database\QueryException  Cannot add foreign key constraint (SQL  
  : alter table `read_wishlist_item_feedbacks` add constraint `read_wishlist_  
  item_feedbacks_wishlist_id_foreign` foreign key (`wishlist_id`) references   
  `wishlists` (`id`))

**Comment by stas727** [comment]
An error with foreign keys in CreateReadWishlistItemFeedbacksTable migration.
Migration must look like this on: 

```php
Schema::create('read_wishlist_item_feedbacks', function (Blueprint $table) {
            $table->increments('id');
            $table->string('wishlist_item_feedback_id');
            $table->integer('user_id')->unsigned();
            $table->foreign('user_id')->references('id')->on('users');
            $table->string('wishlist_id');
            $table->foreign('wishlist_id')->references('id')->on('wishlists');
            $table->string('appliance_id');
            $table->foreign('appliance_id')->references('id')->on('appliances');
            $table->boolean('dislike');
            $table->timestamps();
        });
```

**Comment by josecelano** [comment]
Thanks @stas727 . Fixed.
